### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Ferrothorn** [Natsukage/PostNamazu#1]
目前在用的时候有个报错
尝试从一个网络位置加载程序集，在早期版本的.NET Framework中，这会导致对该程序集进行沙盒处理。此发行版的.NET Framework默认情况下不启用策略，因此，此加载可能会很危险。如果此加载不是要对程序集进行沙盒处理，请启用loadFromRemoteSources开关.有关详细信息，请参见Http://go.microsoft.com/fwlink/?LinkId=155569
国服，游戏版本5.3，FFCAFE版ACT 3.8.3.2sfx
请问该怎么解决？

**Comment by Natsukage** [comment]
报错信息意思是你尝试加载的dll文件位于网络路径上而非本地路径。例如你将2个dll文件放在了网络映射的盘符下。
放在本地硬盘下尝试加载也会报错吗？看一下ACT插件中心中显示的插件路径是什么

**Comment by Ferrothorn** [comment]
我把鲶鱼精邮差的两个.dll文件放在了ACT的那些默认插件的位置，是本地的C盘。ACT显示的插件路径是
FileName: C:\Program Files (x86)\FFCafe\ACT国服整合\Plugins\PostNamazu\PostNamazu.dll

**Comment by Natsukage** [comment]
右键 属性 常规页的最下面（属性：只读/隐藏行 的下面）
看看是否有“此文件来自其他的计算机，可能被阻止以保护您的计算机”选项，如果有的话，解除右侧的锁定并应用后再试一下。

**Comment by Ferrothorn** [comment]
好了，确实是这个问题，谢谢大佬！
