### ISSUE TITLE
在浏览添加启用插件的时候：需要强名称程序集

### ISSUE THREAD

**Issue by 736319147** [Natsukage/PostNamazu#13]
![image](https://user-images.githubusercontent.com/48674272/147873697-774aad06-e1c4-4587-9bc2-6bd2a1041532.png)

**Comment by Natsukage** [comment]
在添加插件后，重启过ACT了吗？如果重启后依然报错，解析插件，高级触发器和邮差的加载顺序没有错误吗？

**Comment by 736319147** [comment]
顺序是解析插件，触发器，邮差，还是报这个错
![image](https://user-images.githubusercontent.com/48674272/147874063-bde1b15c-7867-41d4-85b1-7b2ac3dade9e.png)

**Comment by Natsukage** [comment]
唔，这个是哪个版本的ACT呢？
我这里只试过原版和呆萌的整合版启动器，之前有别人也遇到这个问题，但是用纯净版ACT启动就正常了，我不太确定是不是ACT的问题

**Comment by Beryllium-10** [comment]
碰到了一样的问题。ACT版本是咖啡整合

**Comment by zoy909** [comment]
使用呆萌整合的act也出现了这个错误
![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)

**Comment by Natsukage** [comment]
> 使用呆萌整合的act也出现了这个错误
> ![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)

试一试把邮差的加载顺序挪到紧随解析插件和高级触发器之后，其他插件之前呢？或者先临时禁用其他插件，看看还会不会有提示呢？
邮差本身并没有进行过强签名，正常来说是不应该有强签名引用提示的才对。

**Comment by zoy909** [comment]
> > 使用呆萌整合的act也出现了这个错误
> > ![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)
> 
> 试一试把邮差的加载顺序挪到紧随解析插件和高级触发器之后，其他插件之前呢？或者先临时禁用其他插件，看看还会不会有提示呢？ 邮差本身并没有进行过强签名，正常来说是不应该有强签名引用提示的才对。

![image](https://user-images.githubusercontent.com/69102733/147916592-0fdd3d6c-34d3-402c-bffa-8083c51ac4c8.png)
即使排序并关闭其他插件也依然不行。另外1.2.2.0是可以正常用的。

**Comment by Natsukage** [comment]
> > > 使用呆萌整合的act也出现了这个错误
> > > ![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)
> > 
> > 
> > 试一试把邮差的加载顺序挪到紧随解析插件和高级触发器之后，其他插件之前呢？或者先临时禁用其他插件，看看还会不会有提示呢？ 邮差本身并没有进行过强签名，正常来说是不应该有强签名引用提示的才对。
> 
> ![image](https://user-images.githubusercontent.com/69102733/147916592-0fdd3d6c-34d3-402c-bffa-8083c51ac4c8.png) 即使排序并关闭其他插件也依然不行。另外1.2.2.0是可以正常用的。

1.2.3.0的唯一更新其实只有对应6.0更新的游戏特征码和更新了引用的解析插件版本才对
你的解析插件是哪个版本的？是国服还是国际服客户端？

**Comment by Beryllium-10** [comment]
> > > > 使用呆萌整合的act也出现了这个错误
> > > > ![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)
> > > 
> > > 
> > > 试一试把邮差的加载顺序挪到紧随解析插件和高级触发器之后，其他插件之前呢？或者先临时禁用其他插件，看看还会不会有提示呢？ 邮差本身并没有进行过强签名，正常来说是不应该有强签名引用提示的才对。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69102733/147916592-0fdd3d6c-34d3-402c-bffa-8083c51ac4c8.png) 即使排序并关闭其他插件也依然不行。另外1.2.2.0是可以正常用的。
> 
> 1.2.3.0的唯一更新其实只有对应6.0更新的游戏特征码和更新了引用的解析插件版本才对 你的解析插件是哪个版本的？是国服还是国际服客户端？

我的ACT是国服客户端，咖啡整合，解析插件版本是2.2.1.5（是FFXIV_ACT_Plugin.dll 的版本对吧）。1.2.3.0碰到强签名引用提示问题，下载1.2.2.0可以正常使用

**Comment by Natsukage** [comment]
> > > > > 使用呆萌整合的act也出现了这个错误
> > > > > ![image](https://user-images.githubusercontent.com/69102733/147900768-0b4e0172-9445-46f1-8b0e-42ddf88de29b.png)
> > > > 
> > > > 
> > > > 试一试把邮差的加载顺序挪到紧随解析插件和高级触发器之后，其他插件之前呢？或者先临时禁用其他插件，看看还会不会有提示呢？ 邮差本身并没有进行过强签名，正常来说是不应该有强签名引用提示的才对。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/69102733/147916592-0fdd3d6c-34d3-402c-bffa-8083c51ac4c8.png) 即使排序并关闭其他插件也依然不行。另外1.2.2.0是可以正常用的。
> > 
> > 
> > 1.2.3.0的唯一更新其实只有对应6.0更新的游戏特征码和更新了引用的解析插件版本才对 你的解析插件是哪个版本的？是国服还是国际服客户端？
> 
> 我的ACT是国服客户端，咖啡整合，解析插件版本是2.2.1.5（是FFXIV_ACT_Plugin.dll 的版本对吧）。1.2.3.0碰到强签名引用提示问题，下载1.2.2.0可以正常使用

啊……
在1.2.3.0下载页面上有写，这个版本只适用于2.6.2.3版本后的解析插件。国际服6.0版本的解析插件大幅改动，和之前的解析插件并不兼容。
国服使用在这之前之前版本的解析插件继续使用上一个版本就可以了
