### ISSUE TITLE
鲶鱼精邮差没办法读取进程

### ISSUE THREAD

**Issue by Guard750** [Natsukage/PostNamazu#14]
只会出现正在监听端口，请问怎么处理

**Comment by Guard750** [comment]
![Uploading -7s28Q8fnq-c54wKhT1kSd0-56.jpg…]()

**Comment by Guard750** [comment]
![721061909](https://user-images.githubusercontent.com/97206801/148320093-5908c992-360b-44dd-abbd-a1acea242e2a.jpg)

**Comment by Guard750** [comment]
![721061909](https://user-images.githubusercontent.com/97206801/148320132-bdf9a1e7-e08b-4da7-9534-6bd58bbba1dc.jpg)

**Comment by Natsukage** [comment]
是国服还是国际服？

**Comment by Guard750** [comment]
> 

国服

**Comment by Natsukage** [comment]
国服的话先尝试重启游戏客户端与ACT两者。看看是否问题依旧。这种情况要么是没找到游戏进程，要么是找不到内存特征码
邮差的版本是什么？

**Comment by Guard750** [comment]
> 國服的話先嘗試重啟遊戲客戶端與ACT兩者。看看是否問題依舊。這種情況要么是沒找到遊戲進程，的英文要么找不到內存特徵碼 郵差的版本的英文什麼？

客戶端與act已經有重新啟動過了，端口後來有改成跟解析進程一樣的數字也是一樣，郵差版本是下載1.2.2.0的

**Comment by Natsukage** [comment]
那你确认一下，邮差的dll文件是否有和GrayMagic.dll放在同一个目录下？是否是被杀毒软件拦截了？

**Comment by Guard750** [comment]
> 

是放在一起的，防毒

**Comment by Guard750** [comment]
> 那你確認一下，郵差的dll文件是否有和GrayMagic.dll選擇同一個目錄下？是否是被殺毒軟件攔截了？

兩個文件是一起的，我沒有另外裝防毒，是用w10內建的

**Comment by Guard750** [comment]
![Uploading W{`1BYYWWC$T]]G})V8U3D3(1).png…]()

**Comment by Guard750** [comment]
![W{`1BYYWWC$T G})V8U3D3(1)](https://user-images.githubusercontent.com/97206801/148326769-32ab7a39-0822-4e44-a43a-d64b23517aa1.png)

**Comment by Natsukage** [comment]
[SigTest.zip](https://github.com/Natsukage/PostNamazu/files/7819523/SigTest.zip)
你试试解压后以管理员权限运行里面的SigTest.exe，看一下提示内容，如果正常的话应该会显示9行偏移数值。

**Comment by Guard750** [comment]
![J_7DI_CUEYFPH8X$3M_ZJLL](https://user-images.githubusercontent.com/97206801/148330595-542056c0-56b5-4ee8-ab98-ae23cfc41450.png)
出現這個畫面一閃而過

**Comment by Natsukage** [comment]
……唔，这个错误是压根没找到游戏进程…
你在任务管理器里看一下，你的游戏进程是ffxiv.exe，还是ffxiv_dx11.exe？

**Comment by Guard750** [comment]
![JUYEXFW$J XVY1JV0 CSOVV](https://user-images.githubusercontent.com/97206801/148332126-9070e5cd-e3fb-4d56-b8c2-f5d481ec89af.png)
我剛剛沒有開遊戲，我把遊戲開起來重新按一次了

**Comment by Guard750** [comment]
![LU`IRCEUHABO8 L_{I02_ E](https://user-images.githubusercontent.com/97206801/148332200-96f2f7d9-40b5-4871-b975-5d3d75041bf4.png)
遊戲過程顯示的應該是dx11

**Comment by Natsukage** [comment]
…这个就有点怪了，既然偏移查找没有出问题，那邮差找不到游戏进程唯一的可能就是邮差本身找不到解析插件或graymagic.dll了。但是我确实没在咖啡整合的ACT上试过，我只测试过原版和呆萌的ACT。不太清楚咖啡版ACT是否对插件的运行逻辑有不同处理。
你试试看直接运行纯净版ACT加载插件看看能否找到游戏进程呢？
[ACTv3.zip](https://github.com/Natsukage/PostNamazu/files/7819632/ACTv3.zip)
上面的是原版纯净版ACT，Plugin文件夹中只有解析插件、高级触发器与邮差3个插件，记得要手动用管理员权限运行。否则会找不到游戏。
里面的插件路径可能是乱的，你可能得手动重新添加3个插件后重启ACT看看

**Comment by Guard750** [comment]
> …这个就有点怪了，既然偏移查找没有出问题，那邮差找不到游戏进程唯一的可能就是邮差本身找不到解析插件或graymagic.dll了。但是我确实没在咖啡整合的ACT上试过，我只测试过原版和呆萌的ACT。不太清楚咖啡版ACT是否对插件的运行逻辑有不同处理。 你试试看直接运行纯净版ACT加载插件看看能否找到游戏进程呢？ [ACTv3.zip](https://github.com/Natsukage/PostNamazu/files/7819632/ACTv3.zip) 上面的是原版纯净版ACT，Plugin文件夹中只有解析插件、高级触发器与邮差3个插件，记得要手动用管理员权限运行。否则会找不到游戏。 里面的插件路径可能是乱的，你可能得手动重新添加3个插件后重启ACT看看

純淨版的有出現進程了，我載呆萌的試試，謝謝，辛苦了

**Comment by Guard750** [comment]
![-4ad6d43b9809e82e](https://user-images.githubusercontent.com/97206801/148369739-ff12628b-42e2-4b9c-9e00-35eef7f7ee06.jpg)

**Comment by Natsukage** [comment]
> > …这个就有点怪了，既然偏移查找没有出问题，那邮差找不到游戏进程唯一的可能就是邮差本身找不到解析插件或graymagic.dll了。但是我确实没在咖啡整合的ACT上试过，我只测试过原版和呆萌的ACT。不太清楚咖啡版ACT是否对插件的运行逻辑有不同处理。 你试试看直接运行纯净版ACT加载插件看看能否找到游戏进程呢？ [ACTv3.zip](https://github.com/Natsukage/PostNamazu/files/7819632/ACTv3.zip) 上面的是原版纯净版ACT，Plugin文件夹中只有解析插件、高级触发器与邮差3个插件，记得要手动用管理员权限运行。否则会找不到游戏。 里面的插件路径可能是乱的，你可能得手动重新添加3个插件后重启ACT看看
> 
> 純淨版的有出現進程了，我載呆萌的試試，謝謝，辛苦了

要注意下我发你的解析插件和邮差1.2.3.0版本都是适配国际服的版本，只是为了确认一下是不是ACT的问题。
1.2.3.0版本的邮差更新只是适配了新版本的解析插件和维护了内存特征码，所以按理说如果1.2.3.0版本能用的话，1.2.2.0版本应的邮差该也可以用。

你在实际使用时候一定要换回国服版本的解析插件和1.2.2.0版本邮差试一下。如果发现1.2.3.0版本的邮差和对应的解析插件可以找到游戏，而1.2.2.0邮差与旧版本的解析插件无法找到游戏的话，那就说明问题在别的地方，你再来问我
