### ISSUE TITLE
请问鲶鱼精插件为什么三连桶不会标记数字了 国服

### ISSUE THREAD

**Issue by LuoRenMu** [Natsukage/PostNamazu#16]

**Comment by Natsukage** [comment]
鲶鱼精本身并没有标记的能力，你要先确认一下你的触发器是否正常工作，在应该标记的时候，鲶鱼精的插件页面日志中是否有输出日志？

**Comment by LuoRenMu** [comment]
鲶鱼精的日志报告中 显示输出了/mk attack <1> ~ /mk attack <3>

**Comment by Natsukage** [comment]
如果执行了/mk那就不应该不出现标记才对
你先试试执行/e之类的看看能不能正常输出默语，确认一下鲶鱼精是否正常工作？
然后还需要确定一下是不是有人和你一起开了触发器，因为/mk对同一个目标执行第二次的时候我记得是会取消掉原来的标记的

**Comment by LuoRenMu** [comment]
我知道了 谢谢你
