### ISSUE TITLE
鲶鱼精邮差无法使用

### ISSUE THREAD

**Issue by KnightPeink** [Natsukage/PostNamazu#17]
提示另一个程序正在使用此文件，进程无法访问
![image](https://user-images.githubusercontent.com/73388556/158735714-7b39caf5-4ef8-49fe-a73f-6dd90ce42ce7.png)

**Comment by Natsukage** [comment]
是咖啡act还是呆萌act呢？是用管理员权限启动的程序吗？

**Comment by KnightPeink** [comment]
咖啡ACT，是管理员启动

**Comment by Natsukage** [comment]
邮差的日志中提示什么呢？可以发一下邮差界面的日志嘛

**Comment by KnightPeink** [comment]
![image](https://user-images.githubusercontent.com/73388556/158737102-b6c2799a-fca3-47b1-af4f-b7576c03f8ea.png)

**Comment by Natsukage** [comment]
啊这…
这个有点奇怪，邮差在启动http监听的时候其实是不会写入配置文件的，只有插件退出时候才会写入。所以这个地方按说没道理会提示访问文件冲突。这种情况我也是第一次见。
我刚刚试着用咖啡act启动也没有报错。
会不会是之前退出ACT没有退干净呢？有没有试过重启一下电脑再启动act呢？（不确定）

**Comment by KnightPeink** [comment]
试过重启没用，能否提供一下写入配置文件的位置？我删除一下试试

**Comment by Natsukage** [comment]
ACT主目录下的Config\PostNamazu.config.xml
其实这种情况也有可能是被杀毒软件啥的给拦住了，所以无法访问其他文件，不一定是因为访问配置文件出错的问题，我不是很确定。
但是确实以前从来没见过这个提示……

**Comment by KnightPeink** [comment]
发现2019端口不能启用监听，但是其他端口可以

**Comment by Natsukage** [comment]
……有点怪
那是不是你开着pp或者卫月之类的其他工具，占用了2019端口？

**Comment by KnightPeink** [comment]
自查了一下，没有开着卫月什么的，换端口监听插件还能正常工作吗？

**Comment by arthasxkyang** [comment]
> 自查了一下，没有开着卫月什么的，换端口监听插件还能正常工作吗？

用回调命令可以无视端口，用通用url则注意修改端口好即可。
