### ISSUE TITLE
与OP版本冲突

### ISSUE THREAD

**Issue by IneedHeaaaling** [Natsukage/PostNamazu#18]
咖啡act更新国服6.0解析后，如果保持开启鲶鱼精插件状态打开act，会提示找不到OP版本，导致OP无法使用。关闭鲶鱼精插件，打开act就无异常，且可以在正常启动act后，通过插件列表打开鲶鱼精邮差进行使用。
![image](https://user-images.githubusercontent.com/99547248/158944309-52c09dd6-c3e7-4a3e-92d4-86e2fc342083.png)
![image](https://user-images.githubusercontent.com/99547248/158944353-4d63cb9f-6586-4fca-9946-decbe7cc9ab5.png)

**Comment by Natsukage** [comment]
在咖啡的插件列表页右下角点击“高级管理”
然后将鲶鱼精邮差移动到OverlayPlugin的下方，重启ACT。

咖啡的魔改版悬浮窗刷了很高的版本号，原版的解析插件版本才到0.18.0.0而咖啡的魔改版已经刷到了22.几。然而咖啡的悬浮窗和原版却叫同一个名字。两者实际是不兼容的。
如果将邮差放在悬浮窗插件之后加载，邮差会自动适配之前已经加载过的OverlayPlugin版本，但是如果让邮差提前于OverlayPlugin加载，邮差也不知道接下来会被加载的会是原版OverlayPlugin还是咖啡魔改版悬浮窗插件，图中的情况就是邮差预加载了原版OverlayPlugin的引用，然后随后ACT尝试加载了咖啡的魔改版悬浮窗插件的情况

或者还有另一种方法是抛弃咖啡的魔改版悬浮窗插件使用原版悬浮窗插件，或换用呆萌版ACT，就不会有这个冲突了。

**Comment by IneedHeaaaling** [comment]
感谢回答！非常好用，孩子很开心。
