### ISSUE TITLE
鲶鱼精未能加载文件或程序集

### ISSUE THREAD

**Issue by soriceK** [Natsukage/PostNamazu#19]
[16:54:48] 插件版本:1.3.0.5
[16:54:48] 在2020端口启动监听
[16:54:48] 绑定Triggernometry
[16:54:48] 未能加载文件或程序集“Triggernometry, Version=1.1.4.1, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。不支持操作。 (异常来自 HRESULT:0x80131515)
[16:54:48] 绑定OverlayPlugin
[16:54:51] Getting Offsets......
[16:54:52] 已找到FFXIV进程 14836

插件加载顺序也是正确的，是因为cafeact插件中心自带的Triggernometry版本问题么

**Comment by Natsukage** [comment]
0x80131515 的错误和#1 遇到的错误是一样的，对象dll文件被安全保护策略锁定了
右键Triggernometry的dll，选择属性，然后解除文件锁定应该就好了。

**Comment by Natsukage** [comment]
解除锁定后重新启动过ACT了吗？

**Comment by soriceK** [comment]
> 解除锁定后重新启动过ACT了吗？

我是刚开机就先解除锁定然后开的act，然后我刚刚又重启电脑再开了一次act，依旧是这个报错

**Comment by soriceK** [comment]
![图片](https://user-images.githubusercontent.com/72680331/161287419-00689c1e-bae5-4994-8947-b11898770893.png)
![图片](https://user-images.githubusercontent.com/72680331/161287452-1392c73e-bd35-4896-816e-265c150c4899.png)
我也不知道为啥。。我初次报错日志甚至显示1.1.4.1

**Comment by soriceK** [comment]
> > > 解除锁定后重新启动过ACT了吗？
> > 
> > 
> > 我是刚开机就先解除锁定然后开的act，然后我刚刚又重启电脑再开了一次act，依旧是这个报错
> > 而且咖啡自带的Triggernometry应该是1.1.4.4版本的，不应该会有1.1.4.5版本的引用才对…
> > 我刚试了下咖啡ACT加载没有出现这个错误。能发下你使用的插件列表吗？

![图片](https://user-images.githubusercontent.com/72680331/161291943-7758f366-9baa-4e5d-adef-6930807e8f69.png)
![图片](https://user-images.githubusercontent.com/72680331/161291957-531c6a13-e0d6-409a-a620-d15370da28af.png)
我也不知道为啥。。我初次报错日志甚至显示1.1.4.1

**Comment by Natsukage** [comment]
提示1.1.4.1是没问题的，因为鲶鱼精编译的时候引用的是1.1.4.1版本的Triggernometry文件，但是如果ACT在鲶鱼精之前加载了Triggernometry，鲶鱼精在加载时候可以正常的适应已经加载的1.1.4.4版本Triggernometry
这个1.1.4.5感觉是有某个别的插件加载了其他的Triggernometry引用的感觉…能不能先试试看关闭解析插件、Triggernometry、OverlayPlugin和鲶鱼精外的插件启动，看看会不会报错？

**Comment by Natsukage** [comment]
[PostNamazu.zip](https://github.com/Natsukage/PostNamazu/files/8399032/PostNamazu.zip)
那你试试看用这个鲶鱼精替换之前的鲶鱼精的dll文件看看还会不会报错

**Comment by soriceK** [comment]
> [PostNamazu.zip](https://github.com/Natsukage/PostNamazu/files/8399032/PostNamazu.zip) 那你试试看用这个鲶鱼精替换之前的鲶鱼精的dll文件看看还会不会报错

依旧是这个问题，但是我通过完全清除trn所有的文件解决了这个问题
![图片](https://user-images.githubusercontent.com/72680331/161297343-b208f531-44fa-45b0-9b09-ce2e6a103cf7.png)
应该是尼尼魔改版trn文件残留的问题，1.1.4.5应该是原来的尼尼魔改trn版本号，谢谢大佬解答
