### ISSUE TITLE
调试窗口报错

### ISSUE THREAD

**Issue by fakedestinyck** [Natsukage/PostNamazu#20]
报错内容如下：

> [20:24:45] 插件版本:1.3.0.5
> [20:24:45] 绑定Triggernometry
> [20:24:45] 绑定OverlayPlugin
> [20:24:54] Getting Offsets......
> [20:24:56] 已找到FFXIV进程 11792
> [20:25:24] /p 123
> [20:25:39] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
>    at GreyMagic.Executor.WaitForInjection(Int32 timeout)
>    at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
>    at GreyMagic.Executor.Execute(Byte[] bytes)
>    at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
>    at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
>    at PostNamazu.Actions.Command.DoTextCommand(String command)
>    at PostNamazu.PostNamazu.DoAction(String command, String payload)

用的是咖啡整合，测试的时候使用的是Triggernometry

**Comment by Natsukage** [comment]
这个提示是注入压根没成功……我确实从来没遇到过这种情况
首先排除一下杀毒软件干扰的可能性，然后看一下是不是有其他注入类的工具影响？

**Comment by fakedestinyck** [comment]
就很奇怪因为我压根没有装杀毒软件 我这台电脑上除了装了狒狒也没装别的了 就  迷惑 我再去仔细找找我装了什么吧

**Comment by fakedestinyck** [comment]
再来follow一下这个issue，我后来试了别的卫月是可以用的，作者不知道有没有什么别的idea orz

**Comment by Natsukage** [comment]
卫月和鲶鱼精的注入方式不一样，这个提示是找到了入口点，但是当调用注入的方法时没有收到回应。
理论来说最可能的情况就是被拦截了，我自己在测试时候都从来没遇到过这种情况OTL

**Comment by fakedestinyck** [comment]
感谢大大回复orz
我在想会不会是因为我用的是arm的windows的原因呀 我也不太清楚windows这块的具体原理什么的……就是提供一个猜想

**Comment by Natsukage** [comment]
……啊这，确实我完全没考虑过这点，我也没在arm的windows上测试过…

**Comment by fakedestinyck** [comment]
> 

我找了半天找到一个这个别人也有的类似的问题 不知道作者有没有空去看看有没有帮助orz https://github.com/ChuckHearthstone/SilverFish/issues/39 恨自己不会windows编程

**Comment by Natsukage** [comment]
我看了下这里提到的并不是同一个问题…

**Comment by Natsukage** [comment]
这个例子里的作者是因为注入地址错误，所以不工作
但是这种情况的话，理应是所有人都不工作才对。不会出现一部分人可以工作另一部分人不行的情况

**Comment by Natsukage** [comment]
我还在研究问题的原因
不过总之还是多谢帮助查找相关信息了OTL

**Comment by fakedestinyck** [comment]
哦哦哦原来如此 辛苦了作者大大orz没有机器给你调试着实痛苦 如果有需要的话可以让我来帮忙测~

**Comment by Natsukage** [comment]
更新了1.3.0.6版本，从其他人的反馈来看应该（大概可能）解决了这个问题，你再试一下看看？
如果有问题的话随时回报

**Comment by fakedestinyck** [comment]
悲报……我刚下了新版的又去试了下……还是一样的问题orz

**Comment by fakedestinyck** [comment]
我实在不想搞了，所以我换了个不是arm的电脑 现在问题解决了，要是作者大大实在搞不定的话就当无事发生吧orz感觉有这个问题的也就我一个了））
