### ISSUE TITLE
不能正常使用了，提示异常。

### ISSUE THREAD

**Issue by zkj2716491** [Natsukage/PostNamazu#24]
以前可以，但是我现在测试只有邮差里会显示，但是游戏里不会说话也不会显示
[22:14:23] 插件版本:1.3.0.5
[22:14:23] 在2085端口启动监听
[22:14:23] 绑定Triggernometry
[22:14:23] 绑定OverlayPlugin
[22:14:26] Getting Offsets......
[22:14:26] 已找到FFXIV进程 5916
[22:44:14] /p 已挑衅 <se.4>
[22:44:29] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[11:19:54] /ac 整备
[11:20:09] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[11:23:09] /e 123
[11:23:24] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[11:24:16] /p 已挑衅 <se.4>
[11:24:31] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[11:25:32] /e 已挑衅 <se.4>
[11:25:43] 已停止监听
[11:25:47] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[11:25:53] 在2019端口启动监听
[11:26:02] /e 已挑衅 <se.4>
[11:26:17] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)

**Comment by zkj2716491** [comment]
我看到有人也出现这个问题，我和他一样也是咖啡

**Comment by Natsukage** [comment]
[PostNamazu.zip](https://github.com/Natsukage/PostNamazu/files/8759416/PostNamazu.zip)
试一下这个版本的是否能正常工作呢？

**Comment by zkj2716491** [comment]
好的，谢谢

**Comment by zkj2716491** [comment]
> [PostNamazu.zip](https://github.com/Natsukage/PostNamazu/files/8759416/PostNamazu.zip) 试一下这个版本的是否能正常工作呢？

可以，没问题，非常感谢

**Comment by Natsukage** [comment]
……原来问题出在这里233
我大概下午会更新一下新版本，到时候麻烦你再去更新下release版了。感谢汇报

**Comment by zkj2716491** [comment]
好
