### ISSUE TITLE
测试指令的时候窗口报错

### ISSUE THREAD

**Issue by Duckym** [Natsukage/PostNamazu#26]
[12:07:35] 插件版本:1.3.0.6
[12:07:35] 绑定Triggernometry
[12:07:35] 绑定OverlayPlugin
[12:07:38] Getting Offsets......
[12:07:38] 已找到FFXIV进程 4080
[12:08:04] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: t. Path 'ActorID', line 1, position 13.
   在 Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(Char currentChar, Int32 charPos)
   在 Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   在 Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 PostNamazu.Actions.Mark.DoMarking(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)

**Comment by Natsukage** [comment]
domarking角色标记是需要传递角色id或actorid的，你传递的具体指令内容是什么呢？actorid或者角色名正确吗？
