### ISSUE TITLE
怎么关闭自动标点

### ISSUE THREAD

**Issue by Guard750** [Natsukage/PostNamazu#27]
你好，我触发器检查过都没有改标点的，但只要开启鲶鱼精进副本就会自动改标点，请问怎么关闭自动标点

**Comment by Natsukage** [comment]
邮差自己是不会执行标点的，如果有标点那肯定是有触发器执行的。
除了triggernometry以外，cactbot等悬浮窗轮椅也有可能有标点操作的。建议你再仔细排查一下

**Comment by Guard750** [comment]
> 自己不會有標點的，然後郵差一下有標點那如果有類似類似的類似操作的窗口，肯定是有 可能操作的，也有可能有標點的。

好的，谢谢。我查了很久，没有查到是哪边触发鲶鱼精标点的，请问我有什么办法可以排查哪边触发吗？我是使用呆萌的catbot, 在战场的时候也会出现本地标点在右下

**Comment by Natsukage** [comment]
把触发器依次禁用来排查一下问题出在哪个触发器上
或者直接把所有触发器导出，然后用记事本打开，搜索waymark看看哪里用到了标点指令

**Comment by Souma-Sumire** [comment]
少开点挂，不要赖工具
