### ISSUE TITLE
请问这是怎么回事  提示：需要强名称程序集

### ISSUE THREAD

**Issue by stig141** [Natsukage/PostNamazu#29]
[17:29:57] 插件版本:1.3.0.6
[17:29:57] 绑定Triggernometry
[17:29:57] 绑定OverlayPlugin
[17:34:18] System.IO.FileLoadException: 需要强名称程序集。 (异常来自 HRESULT:0x80131044)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
请问这是怎么回事

**Comment by Natsukage** [comment]
你这个邮差的版本是从邮差的release页面下载的吗…
是不是老版本的GrayMagic.dll文件没有删掉，现在版本的邮差应该只有单文件的。
强签名错误说明邮差引用了不正确的GrayMagic.dll文件，但是目前我不确定你这里加载的文件是来自哪里的。如果在确保以前版本的旧邮差的文件已经删掉的情况下还是出现这种问题的话，需要尝试禁用其他插件，在只保留解析插件、Triggernometry或OverlayPlugin与邮差的情况下再试一次

**Comment by stig141** [comment]
谢谢，我排查禁用了一下插件就可以用了
