### ISSUE TITLE
博兹雅里出问题了

### ISSUE THREAD

**Issue by wyza1234** [Natsukage/PostNamazu#3]
玩的赤魔，给赤魔的循环设置了条件替换键位。
打本和打木桩都OK。
但是进博兹雅之后替换键位断断续续的时而生效时而不生效。

生效的时候替换键位有明显的延迟，而普通情况下基本无延迟。

**Comment by Natsukage** [comment]
这个感觉是高级触发器反应不过来…
之前有人说过bzy里因为人太多日志太多所以匹配的日志太多，触发器处理时候会有延迟。
试试在解析插件的解析模式里只开个人试一下看看？

你可以在高级触发器里执行指令之前加一个滴一声的动作，听一下这个滴声有没有延迟，如果也会延迟的话，就说明是高级触发器本身日志太多匹配不过来了

**Comment by wyza1234** [comment]
> 这个感觉是高级触发器反应不过来…
> 之前有人说过bzy里因为人太多日志太多所以匹配的日志太多，触发器处理时候会有延迟。
> 试试在解析插件的解析模式里只开个人试一下看看？
> 
> 你可以在高级触发器里执行指令之前加一个滴一声的动作，听一下这个滴声有没有延迟，如果也会延迟的话，就说明是高级触发器本身日志太多匹配不过来了

解析模式里只开个人有效果，但还是不够。我试了枪刃的普通连击技能，可以触发。
赤魔的技能监听
`gains the effect of `
` loses the effect `
这里匹配有延迟。
把正则表达式优化一下应该可以解决。
