### ISSUE TITLE
邮差不能正常运行了，可能和其他程序有冲突

### ISSUE THREAD

**Issue by zkj2716491** [Natsukage/PostNamazu#31]
[03:07:05] 插件版本:1.3.0.6
[03:07:05] 绑定Triggernometry
[03:07:05] 绑定OverlayPlugin
[03:07:08] Getting Offsets......
[03:07:08] 已找到FFXIV进程 7628
[03:50:23] 在2019端口启动监听
[03:54:01] /p よろしくお願いします~
[03:54:16] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[03:54:29] /ac 下踢
[03:54:31] /p みなさんお疲れ様でした、あなたは私に「MIP」を与えることができますか？ みんなありがとう(*^▽^*)~<se.1>
[03:54:44] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)
[03:54:59] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   在 GreyMagic.Executor.WaitForInjection(Int32 timeout)
   在 GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   在 GreyMagic.Executor.Execute(Byte[] bytes)
   在 GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   在 GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   在 PostNamazu.Actions.Command.DoTextCommand(String command)
   在 PostNamazu.PostNamazu.DoAction(String command, String payload)

**Comment by zkj2716491** [comment]
新旧方法都不行，之前单独更新发我的那一次可以，然后那天下午统一更新以后就用不了了，可能跟我使用了其他插件有关。

**Comment by Natsukage** [comment]
这个情况是注入游戏成功但是却无法执行。
我目前也没遇到过，实在不清楚是因为什么原因导致的。可能是卫月也可能是杀毒软件或者其他插件。

试试看禁用除了邮差，触发器/cactbot，解析插件外的所有其他插件再启动游戏呢？也还会这样吗？

**Comment by zkj2716491** [comment]
如果不使用其他插件可以正常运行

**Comment by Natsukage** [comment]
啊这…能不能二分法排查一下是哪个插件导致的（）

**Comment by zkj2716491** [comment]
我排除了一下，好像是因为那个可以刷赞跑主线的脚本插件，叫rb，因为国际服重新起号，所以找的这个，我关掉这个就可以了，谢谢~

**Comment by zkj2716491** [comment]
因为我想邮差进游戏自动发送请多多指教和打完发送辛苦了，因为日服喜欢这样，我每次发就没那么麻烦，还有刷赞的时候打完可以求推荐（捂脸）

**Comment by zkj2716491** [comment]
我不会用rb去采集或者做其他事情的，就是用来跑主线和刷赞，刷赞act也可以做到，大佬不要误会o(^▽^)o
