### ISSUE TITLE
游戏过程中随机产生的报错导致游戏直接关闭

### ISSUE THREAD

**Issue by NiGuangOwO** [Natsukage/PostNamazu#34]
![QQ图片20221001115919](https://user-images.githubusercontent.com/26338524/193386706-f5a5bfc6-1617-4d9c-a14e-59bbf4fcb597.png)
使用的是最新1.3.2.0版本

**Comment by Natsukage** [comment]
注入失败会导致游戏直接崩掉的情况很少见（一般都是因为找不到注入点所以根本不执行注入）
你看看是不是开了卫月或者rb之类同样会注入游戏的程序导致了冲突？在不启动其他注入类程序的情况下试试呢？

**Comment by NiGuangOwO** [comment]
> 注入失败会导致游戏直接崩掉的情况很少见（一般都是因为找不到注入点所以根本不执行注入） 你看看是不是开了卫月或者rb之类同样会注入游戏的程序导致了冲突？在不启动其他注入类程序的情况下试试呢？

目前只用了卫月，且在正常使用很长一段时间后偶发产生的，我现在尝试使用旧版本看看会不会产生类似问题

**Comment by Natsukage** [comment]
旧版本和新版本的注入部分应该是没区别的，这里跳的错也是注入时的错，感觉和版本应该没关系
新版本只是加了功能，并没有改动注入部分的代码。

**Comment by NiGuangOwO** [comment]
> 旧版本和新版本的注入部分应该是没区别的，这里跳的错也是注入时的错，感觉和版本应该没关系 新版本只是加了功能，并没有改动注入部分的代码。

我思考了下，可能是游戏先崩溃关闭，导致鲶鱼精注入失败弹出错误，而不是注入出错导致游戏崩溃。如果有其他情况我再回来反馈_(:з」∠)_
