### ISSUE TITLE
如何发送按键到游戏进程

### ISSUE THREAD

**Issue by yhong4** [Natsukage/PostNamazu#35]
您好，请问如何用这个插件把triggemonetry里的按键指令发送到游戏进程，我勾选了sendkey好像没有效果，是否有教程？ 谢谢

**Comment by Natsukage** [comment]
> 您好，请问如何用这个插件把triggemonetry里的按键指令发送到游戏进程，我勾选了sendkey好像没有效果，是否有教程？ 谢谢

我记得Triggernometry自己就有发送按键的功能吧…并不需要借助邮差的。
这个功能是给Cactbot实现Triggernometry的操作用的

**Comment by yhong4** [comment]
Triggernometry目前只能给当前窗口发送，不知道借助邮差能否实现后台发送。

**Comment by Natsukage** [comment]
按键的动作是sendkey，
OverlayPlugin回调指令：callOverlayHandler({call:'PostNamazu', c:'sendkey', p:'{keycode}'});
Triggernometry具名回调指令：sendkey
HTTP请求调用路径：http://127.0.0.1:{你设置的端口}/sendkey

按键的code参考
https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.keys?view=windowsdesktop-6.0

例如发送`27`就是发送`esc`按键

**Comment by yhong4** [comment]
谢谢，我试试

**Comment by yhong4** [comment]
您好，我试了一下Triggernometry具名回调指令，command指令有效但是sendkey指令好像在游戏里无效，可是我log里面是能看到有按键指令。
![1666864269580](https://user-images.githubusercontent.com/41982909/198253653-d8b47104-01ca-4f80-8570-8c568c101d3b.png)
![1666864394834](https://user-images.githubusercontent.com/41982909/198253665-20190c98-de01-4aeb-9a9d-8e6bc25dcde9.png)

**Comment by yhong4** [comment]
试了一下还是无效，没有关闭游戏里面窗口，关了防火墙也不行，邮差有log。不知道被什么阻断了，可是command指令又可以用。

**Comment by Natsukage** [comment]
我刚开游戏试了下是可以正常工作的
command和sendkey使用的实现方式完全不同，command是注入游戏内执行的，而sendkey完全不注入游戏，就是从外部给游戏窗口发送一个按键动作，就像按键精灵一样。所以是可能会被各种奇怪的东西所阻拦的。尤其是一些其他游戏的盾之类的可能都会阻断给其他窗口发送按键指令的操作。
建议你是重启后什么其他游戏都没启动的情况下试一试。除此以外我也没有什么别的好办法了

**Comment by yhong4** [comment]
谢谢，我换了一个电脑试了一下可以发送按键。我研究一下。

**Comment by MnFeN** [comment]
试试这个？
![image](https://user-images.githubusercontent.com/85232361/201759967-becdfa3a-3448-403e-96ca-17125ff9ee2f.png)

**Comment by yhong4** [comment]
@MnFeN 
谢谢回复，请问您用的是哪一个版本的ACT，我这边看到我的ACT这个界面 窗口标题和要发送的Keycode的输入框是禁止填写的参数的。
![WeChat Image_20221115090147](https://user-images.githubusercontent.com/41982909/201777329-2116d89d-6316-4a1a-91f9-2368b878b84e.png)
