### ISSUE TITLE
place标点的yz参数似乎是颠倒的

### ISSUE THREAD

**Issue by DoubieV** [Natsukage/PostNamazu#38]
我想要使用鲶鱼精place标点，通过使用Triggernometry的${_ffxivparty[${_ffxivplayer}].xyz}变量获取到坐标
我发现想要正确标点需要把“Y”设成获取到的z坐标，“Z”设成y坐标，x是正常的🤔
是大家不用这种方式获取坐标吗。还是之前就有这种问题但是修了的话会导致老触发器出问题就没修，只是我孤陋寡闻不知道而已
总之给可能遇到同样的朋友提个醒，我自己摸索半天🤡

**Comment by Natsukage** [comment]
鲶鱼精的场地标点功能使用的是PaisleyPark的格式，最初place功能的设计目的就是为了能兼容PaisleyPark的标点字符串进行标点，这样实际使用时就可以少开一个工具了。

具体可以参考Wiki的[place 场地标点](https://github.com/Natsukage/PostNamazu/wiki/place-%E6%9C%AC%E5%9C%B0%E6%A0%87%E7%82%B9) 页面说明。

trn导出的坐标本身就是和PaisleyPark的顺序不同的，这确实是个相当有年头的问题了，在PaisleyPark的说明里应该有写，我记不太清了。如果按照内存里坐标存放的顺序来看的话，PaisleyPark的顺序才是正确的。

**Comment by Natsukage** [comment]
以及，正常的使用方法是直接使用PaisleyPark导出场地标点为字符串，这段字符串可以直接用于邮差。具体可以参考PaisleyPark的教程

**Comment by DoubieV** [comment]
确实是没有细看PaisleyPark的教程，感谢回复
