### ISSUE TITLE
短时间内连续进行标记-清除操作时，有概率漏标记

### ISSUE THREAD

**Issue by leifengsang** [Natsukage/PostNamazu#39]
rt，测试源码、环境、视频见附件
[bug反馈.zip](https://github.com/Natsukage/PostNamazu/files/10892220/bug.zip)

**Comment by Natsukage** [comment]
在线标记是受服务器控制的，服务器对标记速度有所限制。
如果我没记错的话，具体表现是对同一个目标连续快速上或取消标记会很容易触发，对不同目标的话可以快速连续上标记，但是短时间内也只能上8个人的标记。再多了就会跳错了。具体的限额是不是精确的8次我没仔细测试。
取消标记和标记都是占用相同的额度。

这个我目前没有办法解决，因为是服务器端的限制。只要邮差的日志中有log的话，就说明邮差已经将指令正确发送给游戏了，后续客户端和服务端会如何处理我是控制不了的。

如果是本地标记的话，是没有这个频率限制的。

**Comment by leifengsang** [comment]
那如果用queue延时分开标记是否能解决这个问题

**Comment by Natsukage** [comment]
它的机制好像是一定时间内你总共只能上多少标记这么判定的（大约几秒钟内），并不是如果你短时间连续标记次数过多会被禁止标记功能一段时间这种机制。
具体的你可以游戏内用/mk宏去固定的刷标点试一下，快速连续用宏刷标记应该是会跳红字提示操作过于频繁并有音效的的。因为这个间隔其实不是很长，所以大多数时候很少会遇到。但是如果短时间连续变换标记的话，就很容易触发（就像上面说的，取消标记也相当于一次标记行为，所以全体/mk off后立刻重新标记或者反过来也很容易触发这个限制）
因为这个是服务器判定，我感觉应该是无解的。就算游戏内用宏或者手标也依然会受到这个限制。只能尽可能从触发器逻辑方面想办法降低标记和清除标记操作的频率了。

**Comment by leifengsang** [comment]
ok，我想办法从逻辑上限制一下

**Comment by Loskh** [comment]
![5b0f5fa972add62c95948b6e2b91e80a](https://github.com/Natsukage/PostNamazu/assets/22745697/0d749682-fa03-490d-9fbe-52b075a34d24)
发送标记在客户端层面存在两个限制：

1. 同一个标记500ms内只能标1次
2. 2000ms内只能成功标记8次

目前尚未知晓服务器端是否存在类似的限制。
在连续标记测试.js中，每一秒都会标记8个，被规则2所限制，所以会出现这种情况。
