### ISSUE TITLE
鲶鱼精邮差用不了

### ISSUE THREAD

**Issue by Yamer123** [Natsukage/PostNamazu#4]
有成功用过但是之前把插件卸载了，现在重新下载回来发现用不了，你们说的尝试方法用过了发现没有文字出现，在尝试用尼尼科技的自动发牌触发器的时候出现以下的错误
![image](https://user-images.githubusercontent.com/80949921/111756106-ce44ed00-88d4-11eb-9352-1723461a535a.png) 求大佬帮帮我

**Comment by Natsukage** [comment]
看一下邮差面板里的日志写了什么。
邮差在成功找到游戏进程和收到指令时候应该都会有文字日志，看一下日志是否两者都有显示呢？

**Comment by Yamer123** [comment]
我用test action在邮差看到有出现/e 123的文字 但是在游戏里打/e 123邮差没有接收到

**Comment by Natsukage** [comment]
> 邮差有显示找到游戏进程 我用test action在邮差看到有出现/e 123的文字 但是在游戏里打/e 123邮差没有接收到
> ![image](https://user-images.githubusercontent.com/80949921/111859613-1ae40300-897d-11eb-86bb-aa75397ab99a.png)

邮差本来就不会接到游戏内的文字呀。。邮差的作用是把高级触发器的动作发送至游戏内。
你在游戏内打的文字应该是用高级触发器获取并进行处理，然后再通过邮差发给游戏的。邮差并不能直接获取游戏内你的输入

**Comment by Yamer123** [comment]
![image](https://user-images.githubusercontent.com/80949921/111859745-02281d00-897e-11eb-8283-068a11d7fee7.png)
抱歉没有很详细 我有在高级触发器里写了个触发器 可是在游戏里没有出现文字

**Comment by Natsukage** [comment]
> ![image](https://user-images.githubusercontent.com/80949921/111859745-02281d00-897e-11eb-8283-068a11d7fee7.png)
> 抱歉没有很详细 我有在高级触发器里写了个触发器 可是在游戏里没有出现文字
> 高级触发器应该是没有问题的 因为平常都有在用tts

这个有点奇怪了。。
邮差收到指令却没有投递到游戏内这个情况有些少见。你可否先试一下标点指令看看能否正常使用呢？我看一下是执行指令的问题还是邮差整个就不工作了。

最简单的测试方法是在自己周围随便标记几个场地标点，然后向 place 发送 save。之后在游戏内清空场地标点，再向邮差的 place 发送 load。看看是否能加载标点。

此外，你是在国际服使用的嘛？邮差在1.2版本更新了，command指令关联的游戏内函数，能否麻烦你试一下用1.1.0.1版的邮差，使用旧的端口号方式看看command能否正常执行呢？如果标点正常，旧版本可以执行指令而新版本不行，就说明可能是是这里的更改出了问题。

**Comment by Yamer123** [comment]
请问要怎么向place发送save 我是这方面的小白 对 我是国际服的 换了1.1.0.1版的邮差就算是按test action也没有反应

**Comment by Natsukage** [comment]
> 请问要怎么向place发送save 我是这方面的小白 对 我是国际服的 换了1.1.0.1版的邮差就算是按test action也没有反应 以下是error 最新版本的邮差虽然有显示接收到但还是出现了下列error
> ![image](https://user-images.githubusercontent.com/80949921/111861991-3525dd00-898d-11eb-86f6-d89697a664e0.png)

1.1.0.1版本的邮差只支持使用JSON方式提交，你可以参考https://github.com/Natsukage/PostNamazu/blob/master/README.md
里的 使用方法（旧）这一部分。
这个Invoke callback是1.2才开始新增加的使用方法，同时1.2版本更改了发送指令的方式，但是新的发送指令方式是在国服客户端测试的，所以我不确定是不是国际服那边和国服不一样。所以才希望你用1.1.0.1版本通过JSON提交的旧方式试一下能不能使用。

向Place发送save可以参考上面说明里的 PaisleyPark兼容 部分，简单说就是把DoTextCommand改成place，然后下面的/e 123也就是指令内容改成save，然后test action，这个指令的意思是暂存当前场地标点。然后在游戏里清楚场地标点后再向place发送load，看一下是否能够恢复场地标点。

**Comment by Yamer123** [comment]
可以欸

**Comment by Natsukage** [comment]
> 可以欸 我是用新版的

标点正常但是指令不工作而且tr报错这个有点怪，感觉这两者甚至都不是同一个问题……
先确认下你的客户端是开启了默语频道的显示的吧？你直接在游戏聊天框里打/e 123的话，能在聊天框里看到123的灰色文字提示吗？

**Comment by Yamer123** [comment]
原来是我客户端的问题没有开默语频道的显示

**Comment by Yamer123** [comment]
弄了那么久结果是这个问题 辛苦大佬帮忙了了
