### ISSUE TITLE
Support FFXIV Korean Version

### ISSUE THREAD

**Issue by lee-jinhwan** [Natsukage/PostNamazu#44]
I want to support for the FFXIV Korean version.
Can you explain how to get signature of functions?

FFXIVClientStructs is a global version only, so it is hard to signatrues. 
Any references would be appreciated.

**Comment by Natsukage** [comment]
PostNamazu is designed to be compatible with both the official and Chinese servers of FFXIV, so in theory, it should also work with the Korean server. If for some reason it does not, please provide more details so we can look into it.

Additionally, it's important to note that I am not aware of the current game version for the Korean server. The 1.3.2.6 release of PostNamazu is compatible only with FFXIV clients updated to version 6.4 or later. If you are running a version of FFXIV prior to (lower than)6.4, you must use PostNamazu version 1.3.2.5, as there were significant changes in the game's structure in version 6.4 (such as additional types of marks) that make it incompatible with previous versions.

I hope this helps. Any further information you can provide would be greatly appreciated.

**Comment by lee-jinhwan** [comment]
Thank you for the answer.

The current version of Korea server is 6.35. Actually, everything I want works in version 1.3.2.6. However, sometimes the signature is different depending on the client country and I wanted to be prepared for that.

I'll let you know if there are any other issues.
Thanks.
