### ISSUE TITLE
可否支持第三方插件提供的额外指令？

### ISSUE THREAD

**Issue by FrozenJingle** [Natsukage/PostNamazu#46]
对于非游戏自带的指令，有办法让他们像不输入/前缀那样直接输入到聊天栏执行吗？

**Comment by Natsukage** [comment]
command指令中填入的内容和直接输入到聊天栏没区别的（只是不会留下历史记录）
例如你直接command输出“你好”，那就和你在聊天栏直接输入了“你好”2个字一样，会默认在当前频道发言。

对于其他插件的支持情况你可以自己测试一下，理论来说应该是可以支持的

**Comment by FrozenJingle** [comment]
感谢回复，我现在自己测试的情况是游戏内的指令都能正常执行，直接发言也没问题。但是只要是Dalamud插件提供的指令都不能行，在游戏内正常输入是有效的。

**Comment by Natsukage** [comment]
那就意味着卫月拦截的是比较标层的函数，比邮差调用的这个还要早，这就完全是我了解范围之外的了，抱歉（……
我其实弃坑挺久了，不太了解现在卫月的工作原理。

**Comment by FrozenJingle** [comment]
好的，十分感谢您。
