### ISSUE TITLE
关于post请求。

### ISSUE THREAD

**Issue by slbidd** [Natsukage/PostNamazu#49]
您好，是这样的，我想制作一款比较方便的RP小游戏工具，需要自动在ff14里发送消息。前几天逛论坛的时候看到了鲶鱼精可以在游戏里发送消息，wiki里提到了可以用http请求。

在我进行post请求的时，短的消息可以正常发送，稍长一点的中文消息只有一部分可以发送，纯英文数字倒是可以正常发送。是data有长度限制吗，还是我那里搞错了。

实在抱歉，打扰到您了。

`import requests

url = 'http://127.0.0.1:2019/command'
d = message
header = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60'}
r = requests.post(url, headers=header,data=d)`

![9R%`6~O$0EV52XG}B%UXNM](https://github.com/Natsukage/PostNamazu/assets/96671704/9f2f22e4-c5ce-4a0f-a95c-986772b621ef)
![image](https://github.com/Natsukage/PostNamazu/assets/96671704/c4ddb33b-07ed-43ef-9612-031fc72b2e50)
![image](https://github.com/Natsukage/PostNamazu/assets/96671704/6619fc8f-7ea1-41c2-85f0-e87a67138f84)
![image](https://github.com/Natsukage/PostNamazu/assets/96671704/54a7b2ef-d4b9-415b-b261-13134e1763c1)
![image](https://github.com/Natsukage/PostNamazu/assets/96671704/2bedf541-f604-4a9f-a5bb-e8836943ea52)

**Comment by slbidd** [comment]
d = '/e 一二三四五六七八九十十一十二十三十四'
游戏内会发送一二三四五六
d = '/e 一二三四五七八九十十一十二十三十四'
游戏内会发送一二三四五
d = '/e 一二三四七八九十十一十二十三十四'
游戏内会发送一二三四七
d = '/e 一二三四六七八九十十一十二十三十四'
游戏内会发送一二三四六

好奇怪

**Comment by Natsukage** [comment]
默认情况下，requests 将数据发送为 application/x-www-form-urlencoded 类型，它会将数据编码为 ASCII。当您发送非 ASCII 字符（如中文字符）时，如果未正确处理，可能会导致数据被截断或损坏。邮差正常情况下接收的是utf8编码后的字符串

你可以试试强制将文字编码为utf-8
d = '/e 一二三四五六七八九十十一十二十三十四'.encode('utf-8')

另外，header里面关于浏览器类型之类的声明其实是不必要的（

**Comment by slbidd** [comment]
好了 ！！谢谢您！！！！！！！！！！！
