### ISSUE TITLE
请问PostNamazu.dll这个文件在哪

### ISSUE THREAD

**Issue by treeofsoda** [Natsukage/PostNamazu#5]

**Comment by Natsukage** [comment]
下载压缩包放到除了act根目录以外随便什么目录下都可以。。
通常建议是在act目录的plugins目录下新建PostN amazu文件夹，把2个dll丢进去。

**Comment by treeofsoda** [comment]
我在code里没有找到"PostNamazu.dll"这个文件，解压缩之后只有GreyMagic.dll一个dll文件
![image](https://user-images.githubusercontent.com/33137542/113356629-67bdc700-92f7-11eb-9e31-ab3b51cff182.png)

**Comment by Natsukage** [comment]
……你要去下载release里编译版本啊。
直接下源码的话需要自己编译的

**Comment by treeofsoda** [comment]
肥肠爆芡，没看到release orz
