### ISSUE TITLE
国际服5.5更新后的问题

### ISSUE THREAD

**Issue by gn1394594329** [Natsukage/PostNamazu#6]
[12:05:22] Getting Offsets......
[12:05:22] 查找失败：找不到特征值
[12:06:58] Getting Offsets......
[12:06:59] 查找失败：找不到特征值

**Comment by Natsukage** [comment]
抱歉久等
请更新1.2.2.0版本试一下是否可以正常工作。

**Comment by gn1394594329** [comment]
似乎打包错了，因为我更新后发现还是不能用，在插件列表他显示的Version依然是1.2.1.1

**Comment by Natsukage** [comment]
> 似乎打包错了，因为我更新后发现还是不能用，在插件列表他显示的Version依然是1.2.1.1

……溴大了，等我回家重新打包下233

**Comment by Natsukage** [comment]
好了，这次应该没错了…
麻烦重新试一下

**Comment by gn1394594329** [comment]
可以了，谢谢大老
