### ISSUE TITLE
1.3.3.1版本无法注入进程

### ISSUE THREAD

**Issue by Anzusull** [Natsukage/PostNamazu#63]
回退到上个版本才能成功注入，排除变量后确认在cafe ACT中本机环境下1.3.3.1版本无法正常运行，不能确定是否可在其他环境下复现

**Comment by Natsukage** [comment]
你是不是国服客户端（
这个更新应该是面向日服7.0更新的
如果你需要分离了command和donormalcommand，但是特征码依然保留的版本可以下载action中的这个中间版本
https://github.com/Natsukage/PostNamazu/actions/runs/9699117182
