### ISSUE TITLE
1.3.4.0版本无法注入,已被其他进程注入?

### ISSUE THREAD

**Issue by imrepusle** [Natsukage/PostNamazu#67]
国服版本
![微信截图_20240719182756](https://github.com/user-attachments/assets/19b92843-e037-4938-8611-8fa2fc8e3baf)

**Comment by Natsukage** [comment]
1.3.3.1之后的几个更新内容都是为了适配国际服7.0和Triggernometry的新改动的。国服目前版本继续使用1.3.3.0或更早的版本就可以了
