### ISSUE TITLE
插件初始化失败

### ISSUE THREAD

**Issue by makalr61** [Natsukage/PostNamazu#69]
你好！我无法正常添加插件，以下是报错窗口：
![初始化失败](https://github.com/user-attachments/assets/8c865b96-8e01-4e2b-b8f7-bdde6d2897df)

我使用的ACT是呆萌整合，版本号：6.58.1.01
下载的插件版本是:1.3.3.0
请问我该如何处理？

**Comment by Natsukage** [comment]
看起来你使用的解析插件版本太古老了，你用的是魔改版解析插件吗？按说现在新版本的解析插件版本号不该这么低啊（

**Comment by makalr61** [comment]
可能是因为最近回坑更新ACT的时候是放在原来的文件夹里，ACT默认用的还是古早版本的插件，我重新安装了一遍ACT现在已经没问题啦！非常感谢！
