### ISSUE TITLE
7.0国服更新完之后，用1.3.3.1-1.3.4.0版本都提示索引超出范围。

### ISSUE THREAD

**Issue by pockem** [Natsukage/PostNamazu#70]
[16:17:12] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PostNamazu.Common.SigScanner.ScanText(String pattern)
   在 PostNamazu.Actions.Command.GetOffsets()
   在 PostNamazu.Actions.NamazuModule.Setup()

[16:17:12] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PostNamazu.Common.SigScanner.ScanText(String pattern)
   在 PostNamazu.Actions.NormalCommand.GetOffsets()
   在 PostNamazu.Actions.NamazuModule.Setup()

[16:17:12] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PostNamazu.Common.SigScanner.ScanText(String pattern)
   在 PostNamazu.Actions.Preset.GetOffsets()
   在 PostNamazu.Actions.NamazuModule.Setup()

连续弹出三条，不知道是哪个原因，ACT也重装过了

**Comment by zfxsquare** [comment]
等更新
