### ISSUE TITLE
关于鲶鱼精邮差使用时初始化NormalCommand模组失败的问题

### ISSUE THREAD

**Issue by Hyuwan0** [Natsukage/PostNamazu#78]
作者您好！
    我在使用鲶鱼精邮差时遇到了一些问题，以至于无法正常使用。具体表现为在游戏中没有任何反应。请问应该如何解决呢？
    非常感谢您能抽空查看该条求助。谢谢！

日志如下：

[17:18:12] 插件版本：1.3.5.3。
[17:18:12] 在 2019 端口启动 HTTP 监听。
[17:18:12] 已绑定 Triggernometry。
[17:18:12] 已绑定 OverlayPlugin。
[17:18:15] 正在扫描内存特征……
[17:18:15] 已找到 FFXIV 进程 8252。
[17:18:16] 已设置为国际服配置（根据内存信息判断）。
[17:18:16] 初始化 NormalCommand 模组失败：
扫描 ProcessChatBoxPtr 时未匹配到所需的内存签名。 
   場所 PostNamazu.Common.SigScanner.ScanText(String pattern, String name)
   場所 PostNamazu.Actions.NormalCommand.GetOffsets()
   場所 PostNamazu.Actions.NamazuModule.Setup()

状态更新：个人感觉是触发器里面的关键词是中文，而我客户端不是中文导致的问题，与插件无关。不确定，我再调一调

**Comment by MnFeN** [comment]
只是那一个模组失效了，不影响其他的正常工作。据说 7.0 以后 command 新找的函数也可以发送卫月指令了，所以可能之后直接删掉了（我没装卫月，没测试过

**Comment by Hyuwan0** [comment]
> 同样的初始化NoramlCommand模组失败，本人国际服无法使用触发器（或许是7.1需要更新鲶鱼精），其他人可以使用吗

我也是，无法使用鲶鱼精的触发器

**Comment by MnFeN** [comment]
![image](https://github.com/user-attachments/assets/0353cc83-da7d-4d07-af49-4646bc509a14)

除了 NormalCommand 以外没有任何问题，建议检查解析插件、触发器插件等有没有更新

**Comment by Hyuwan0** [comment]
> ![image](https://private-user-images.githubusercontent.com/85232361/387520900-0353cc83-da7d-4d07-af49-4646bc509a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzkyMTYsIm5iZiI6MTczMjM3ODkxNiwicGF0aCI6Ii84NTIzMjM2MS8zODc1MjA5MDAtMDM1M2NjODMtZGE3ZC00ZDA3LWFmNDktNDY0NmJjNTA5YTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE2MjE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNDk2OGM5NzFlMzVkNzVjYjg0ZDEyZGQwNjFhZDQ2Y2UwYmE1OTdlNzljOWIwMWJlNTNmZDBhZWRjOWMwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cedmROKuDLbLFYnrlhiYrsR2Ryd7fNkz8VsdVZXf5eI)
> 
> 除了 NormalCommand 以外没有任何问题
> 
> 建议检查一下插件版本：
> 
> > 鲶鱼精 1.3.5.3
> > 解析插件 2.7.2.0
> > 触发器 1.2.0.7+

好的感谢qwq
