### ISSUE TITLE
能否支持一下跨域？

### ISSUE THREAD

**Issue by Trim21** [Natsukage/PostNamazu#8]
我现在想在cactbot的触发器里面用鲶鱼精，触发器的运行环境是嵌入式的浏览器，在其中发请求需要服务端的跨域支持。
只能额外开一个http服务器进行转发。希望鲶鱼精能原生支持一下跨域请求。

**Comment by Natsukage** [comment]
还真没考虑过cactbot的情况…你试试看这个版本可以工作不？
[PostNamazu.zip](https://github.com/Natsukage/PostNamazu/files/6379755/PostNamazu.zip)

**Comment by Natsukage** [comment]
原来是这种需求…
那前面的版本应该是不能用的，我理解错你的意思了。
不过我记得之前牙刷大佬说过cactbot钓鱼邮差并不需要跨域来的，你等我问下他233。

**Comment by Trim21** [comment]
感谢，忘了可以不要响应了
