### ISSUE TITLE
国服5.5适配问题

### ISSUE THREAD

**Issue by kannadukiise** [Natsukage/PostNamazu#9]
你好，最近使用中发现本地标点功能失效了，请问是否是当前版本不适配国服5.5的原因？

**Comment by Natsukage** [comment]
当前版本（1.2.2.0）是支持国服的。
邮差的日志上是怎么显示的？

**Comment by kannadukiise** [comment]
我又试了一下，确定鲶鱼精是可用的，不可用的部分应该是小龙俯冲触发器的问题，谢谢！
